### ISSUE TITLE
In `recycler.py`, prioritize one kind of strategy based on moony conditions

### ISSUE THREAD

**Issue by seanmacb** [SSantosLab/Main-Injector#10]
Currently, moony vs. notmoony strategy is arbitrarily called 
Using astropy, write a short function to determine which strategy should be used first

**Comment by nixnyxnyx** [comment]
It seems like both moony and notmoony are currently run no matter what. Is this the desired behavior? Should only one be run? What is the criteria for moony vs notmoony? @seanmacb @elisekesler

**Comment by seanmacb** [comment]
Open discussion. We discussed with Marcelle, who wanted to also include rise-set time, and other params

What is the fastest turnaround for strategy -> observing? 1 hour? we should probably just prioritize one of them using whatever future time will be the time observations *would* start.

If these run in parallel, then this is not a problem though

**Comment by seanmacb** [comment]
@nixnyxnyx I think 'threshold for moony' was 66% illumination - that is what is listed on the [MISOAP](https://seanmacb.notion.site/Main-Injector-Standard-OperAting-Procedure-MISOAP-d9795b62a2644bae8daf4f2c990b40cd). Though, that line has a comment to check with the strategy paper...

**Comment by seanmacb** [comment]
These appear to run in parallel, so I am closing the issue
