### ISSUE TITLE
RA flip

### ISSUE THREAD

**Issue by seanmacb** [SSantosLab/Main-Injector#13]
Output .json has RA_json = RA_true - 360
Simple one-line fix before .json write does not resolve issue

**Comment by nixnyxnyx** [comment]
This line looks very suspicious: https://github.com/SSantosLab/Main-Injector/blob/42c06fb248a770d54d6776606c2859badc1e28ad/python/hp2np.py#L96

If this means that OneRing works as intended, then we should just implement a fix at the end when writing to json. However, this makes me want to reevaluate if OneRing is really working as intended and pointing at the right spot. Can we verify this? @seanmacb @elisekesler

**Comment by seanmacb** [comment]
@nixnyxnyx Agreed. On if this is a OneRing functionality, I do not know. That is @elisekesler's domain. 
We tried a one line fix before the .json write, and it did not work (???)

For the line above, when I get the opportunity, I will run in my test directory with this line commented out and see how it works

**Comment by nixnyxnyx** [comment]
I would not comment it out, I would just get rid of the `-360.`

**Comment by seanmacb** [comment]
Will do shortly, just waiting to confirm #14 runs to completion and outputs properly

**Comment by nixnyxnyx** [comment]
That line in `hp2np.py` has been there since the beginning of MI, which makes me suspicious because when Andres ran strategy we didn't have this RA problem. Does this problem still happen with old OneRing?

**Comment by seanmacb** [comment]
Looks like it is a DECam convention and info was not passed to next generation - closing issue
