### ISSUE TITLE
Multi-order skymaps compatibility - short term

### ISSUE THREAD

**Issue by seanmacb** [SSantosLab/Main-Injector#14]
per @nixnyxnyx, all bayestar output going forward will be multiorder. For now, it would be good to get a short term fix to flatten the skymaps. But for now, there is a ligo.skymap command line command that flattens skymaps [here](https://lscsoft.docs.ligo.org/ligo.skymap/tool/ligo_skymap_flatten.html). This is the fastest flattening method we have found. we should put a check in MI that flattens the maps if they are multiorder

**Comment by nixnyxnyx** [comment]
via [L128](https://github.com/SSantosLab/Main-Injector/blob/42c06fb248a770d54d6776606c2859badc1e28ad/handlers/gwstreamer.py#L128) and [L269](https://github.com/SSantosLab/Main-Injector/blob/42c06fb248a770d54d6776606c2859badc1e28ad/handlers/gwstreamer.py#L269) it looks like GWstreamer is already flattening skymaps that it gets from listener, although it's in an inefficient way. My concern is that when MI is given test skymaps, it doesn't have the same check to flatten the skymaps.

**Comment by nixnyxnyx** [comment]
Looks like because the skymap flattening happens in gwstreamer, the test code which runs from recycler does not flatten the maps. I think best practice would be to move the flattening from gwstreamer to recycler.

**Comment by nixnyxnyx** [comment]
Pull request for fix made at #18.

**Comment by nixnyxnyx** [comment]
Merge works. Closing.
