### ISSUE TITLE
SLIPS from `mock-bayestar` mode are not being posted to the webserver

### ISSUE THREAD

**Issue by seanmacb** [SSantosLab/Main-Injector#28]
SLIP moon and skymap plot are not being posted to the webserver when listener is being run in `mock-bayestar` mode

**Comment by nixnyxnyx** [comment]
In these lines `gwstreamer.py` tries to access the webserver:
https://github.com/SSantosLab/Main-Injector/blob/f7851dc21e7c31f7f24b7e645cfbf051630cfa62/handlers/gwstreamer.py#L306-L308

Currently this returns the following errors in the stdout:
```
Permission denied (gssapi-keyex,gssapi-with-mic).
Permission denied (gssapi-keyex,gssapi-with-mic).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]
```
Seems like an authorization issue. Do we still have access to this server?

**Comment by seanmacb** [comment]
We do still have access to the server. We are moving over to a different webserver soon. For now, let's not worry about this, but note the lines we will have to change for the new webserver
