### ISSUE TITLE
Add permissions handling

### ISSUE THREAD

**Issue by elisefuller** [SSantosLab/Main-Injector#30]
Automatically chmod files created throughout Main Injector so there aren't permission issues with different users running it

**Comment by seanmacb** [comment]
Working a bit better, but have not confirmed if we have posted yet

**Comment by seanmacb** [comment]
Just need to add `os.chmod(Filename, 0o0777)` to any written files in `kn_strategy_sims_MI.py`, otherwise we are done

**Comment by seanmacb** [comment]
Finished - awaiting review
