### ISSUE TITLE
Strategy KN weight files written in root directory

### ISSUE THREAD

**Issue by nixnyxnyx** [SSantosLab/Main-Injector#33]
Three files from strategy, `kn_mag_plot_clecio_loglan5.png`, `kn_weights_ids_typebluepriorgaussian_narrow.npy`, and `kn_weights_typebluepriorgaussian_narrow.npy`, are being written in the root directory instead of in the output directory. I don't think this was happening before and it's unclear why it is happening. Doesn't seem to effect output.

**Comment by seanmacb** [comment]
See [here](https://github.com/SSantosLab/Main-Injector/blob/master/python/knlc/kn_strategy_sims_MI.py#L1051-L1084) for the weights files

**Comment by seanmacb** [comment]
See [here](https://github.com/SSantosLab/Main-Injector/blob/master/python/knlc/kn_strategy_sims_MI.py#L1681-L1692) for the plot

**Comment by nixnyxnyx** [comment]
Per André, the weights files should be static on a per-run basis, and the plot seems to change every time. I pointed them each to their respective directories.
