### ISSUE TITLE
Emergency list

### ISSUE THREAD

**Issue by seanmacb** [SSantosLab/Main-Injector#42]
Emergency list needs updating/revision - see [here](https://github.com/SSantosLab/Main-Injector/blob/357df2dd4c43c86e3426d2b353006cfa9d2b83c6/handlers/emails.py#L105-L120)

**Comment by seanmacb** [comment]
Planning to add @nixnyxnyx and myself - sound ok?

**Comment by nixnyxnyx** [comment]
yup
