### ISSUE TITLE
Weather!!!!!!!!

### ISSUE THREAD

**Issue by nfshermy** [SSantosLab/Main-Injector#50]
Please add a bot to post the weather every time we have an update to the map.

**Comment by seanmacb** [comment]
https://noirlab.edu/science/index.php/observing-noirlab/observing-ctio/cerro-tololo/bad-weather-protocol-at-ctio

**Comment by seanmacb** [comment]
I would like to add a more informative weather bot post based on the [CTIO protocols](https://noirlab.edu/science/index.php/observing-noirlab/observing-ctio/cerro-tololo/bad-weather-protocol-at-ctio)

Must include
- Precipitation chance
- Wind
- Humidity
- T_{mirror} - T_{dew}
